name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install

    - name: Run tests script
      shell: bash
      run: ./run-tests.sh

    - name: PHPUnit Tests
      uses: php-actions/phpunit@v3
      env:
        XDEBUG_MODE: coverage
      with:
        bootstrap: ./vendor/autoload.php
        configuration: ./tests/phpunit.config.xml
        php_extensions: xdebug
        args: tests --coverage-clover ./tests/coverage.xml

    - name: Echo coverage
      shell: bash
      run: cat ./tests/coverage.xml

    - name: Upload codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./tests/coverage.xml
